
import React from "react";
import { type NextPage } from "next";
import Head from "next/head";
import { Card } from "../components/Card";

const FindBuilds: NextPage = () => {
    return (
        <>
        <Head>
            <title>Create T3 App</title>
            <meta name="description" content="Generated by create-t3-app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="flex min-h-screen flex-col items-center justify-center gap-8 text-black dark:text-white dark:bg-gray-800">
            <h1>Select your character</h1>
            <ul className="grid grid-cols-3 gap-4">
                <li>
                    <Card raceImageSrc={'./gon.jpg'} raceName={'Gon'}></Card>
                </li>
                <li>
                    <Card raceImageSrc={'./hisoka.jpg'} raceName={'Hisoka'}></Card>
                </li>
                <li>
                    <Card raceImageSrc={'./killua.jpg'} raceName={'Killua'}></Card>
                </li>
            </ul>
        </main>
        </>
    )
}

export default FindBuilds;