import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";


const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center gap-8 text-black dark:text-white dark:bg-gray-800">
        <h1>Welcome!</h1>
        <Link href="/submit-build">Submit a new build</Link>
        <Link href="/builds">View Builds</Link>
      </main>
    </>
  );
};

export default Home;